services:
  jupyter:
    build: .
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_PASSWORD=Hrd12345
    restart: always
    network_mode: host
